language: node_js

node_js:
  - "0.10"

before_script:
  - "npm install -g selenium-standalone bower"
  - "selenium-standalone install && selenium-standalone start > /dev/null 2>&1 &"
  - "node test/app/scripts/web-server.js > /dev/null &"
  - "cd test/app && bower install && cd ../../"

env:
  - BROWSER=phantomjs

addons:
  sauce_connect: true
# Wait for saucelab to respond on `timeouts` calls
# http://support.saucelabs.com/forums/21034924-Open-Sauce-Support
# env:
#   global:
#   - SAUCE_USERNAME=webdriverjs-angular
#   - secure: fPeUCYHS1Y/VF7rPcWCtMaRfvhzcuaTzyAa3nqsk1ERHMh+LfxjY3PspRs9EeG2p4y1YSkE5sPpobyB9uU/ColHXfGhyojVsleRQhUCl7ZZOUyGgLD5pbN2wc5lMBrK4SY5BsdfXzhbADzOSnocJQuAC6uYUJZzVZm31hfd5ZQU=
#   matrix:
#   - BROWSER=chrome
#   - BROWSER=firefox
#   - BROWSER=explorer
#   - BROWSER=iphone
#   - BROWSER=ipad
#   - BROWSER=phantomjs
#   - BROWSER=android
